services:
  - type: web
    name: notes-performance-app
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ASSISTANT_KEY
        generateValue: true
